<a href="https://colab.research.google.com/github/RamMohanHota/ML-and-PYTHON-LAB/blob/main/_01_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
list_1=[3,2,7]
arr_1=np.array(list_1,dtype=np.int16)
print(arr_1)
arr_1=np.array((3,2,7),dtype=np.float64)
print(arr_1)

[3 2 7]
[3. 2. 7.]


In [2]:
list_m=[[1,2,3],[4,5,6],[7,8,9]]
arr_m=np.array(list_m,dtype=np.int16)
print(arr_m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
arr_0=np.ones((2,4),dtype=np.int32)
print(arr_0)


[[1 1 1 1]
 [1 1 1 1]]


In [4]:
arr_0=np.zeros((2,4),dtype=np.int32)
print(arr_0)

[[0 0 0 0]
 [0 0 0 0]]


In [5]:
arr_c=np.full((2,3),8)
print(arr_c)

[[8 8 8]
 [8 8 8]]


In [6]:
arr_1=np.linspace(0,10,5)
print(arr_1)

[ 0.   2.5  5.   7.5 10. ]


In [7]:
arr=np.arange(1,15,2)
print(arr)

[ 1  3  5  7  9 11 13]


In [8]:
arr_r=np.random.random((2,2))
print(arr_r)

[[0.41818473 0.85590822]
 [0.93746025 0.55449608]]


In [9]:
arr_r=np.random.randint(1,19,7)
print(arr_r)

[14 10 14 12  2  9 12]


In [10]:
arr_r=np.random.randn(10)
print(arr_r)

[ 2.79048113e-01  6.92856647e-01 -4.44390138e-02 -4.93715319e-04
 -1.74262724e+00 -6.78284119e-01 -2.06809038e-01  2.02676863e+00
 -1.45650522e+00  2.44033022e-01]


In [11]:
arr_1=np.eye(4)
print(arr_1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
import numpy as np
x2=[(1,2,3),(4,5)]
a2=np.asarray(x2, dtype=object)
print(a2)

[(1, 2, 3) (4, 5)]


In [13]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
arr_1=arr.reshape(3,2)
print(arr_1)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
x = np.array([[3,2,1],[4,6,1]])
print(x.size)

6


In [15]:
x = np.array([[3,2,1],[4,6,1]])
x.itemsize

8

In [16]:
x = np.array([[1,2,3],[4,5,6],[3,4,7]])
x.ndim

2

In [17]:
#.take

x=np.array([1,2,3,4,5])
print(x.take(2))

3


In [18]:
arr = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(arr)
print(arr[0:1])
print(arr[0:3,0:1])
print(arr[1:2,1:2])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
[[1 2 3]]
[[1]
 [3]
 [4]]
[[4]]


In [19]:

new=arr[1:2,1:2]
print(new.shape)

(1, 1)


In [20]:
arr = np.array([[1,2,3],[9,4,5],[11,14,6]])
print(arr.min(axis=1))
print(arr.max(axis=0))

[1 4 6]
[11 14  6]
