In [1]:
import numpy
numpy.__version__

import numpy as np

In [2]:
#Write a program to create a 1D NumPy array of numbers from 1 to 10 and print it.
import numpy as np
array = np.arange(1, 11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
#Create a 3X3 array of zeros and a 2Ö 4 array of ones. Print both arrays.
import numpy as np
zeros_array = np.zeros((3, 3))
ones_array = np.ones((3,3))
print(zeros_array)
print(ones_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
#Create a NumPy array containing numbers from 5 to 50 with a step size of 5 and print it.
import numpy as np
array = np.arange(5, 51, 5)
print(array)

[ 5 10 15 20 25 30 35 40 45 50]


In [5]:
#Create an array of numbers 1-12 and reshape it into a 3Ö 4 matrix and print it.
import numpy as np
array = np.arange(1, 13).reshape(3, 4)
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
#Create two array of same size and compute addition, subtraction, multiplication and division of these arrays and print the results.
import numpy as np
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2
print(addition)
print(subtraction)
print(multiplication)
print(division)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [7]:
#Create a 1D array from 10 to 100 with step 10, and print: First three elements, Last three elements, Every second element
import numpy as np
array = np.arange(10, 101, 10)
print(array[:3])
print(array[-3:])
print(array[::2])

[10 20 30]
[ 80  90 100]
[10 30 50 70 90]


In [8]:
#Create a NumPy array of numbers 120. Extract all elements divisible by 3.
import numpy as np
array = np.arange(120)
divisible_by_3 = array[array % 3 == 0]
print(divisible_by_3)

[  0   3   6   9  12  15  18  21  24  27  30  33  36  39  42  45  48  51
  54  57  60  63  66  69  72  75  78  81  84  87  90  93  96  99 102 105
 108 111 114 117]


In [9]:
#Given an array of random integers between 1100 (size 10), compute: Mean , Median, Standard deviation.
array=np.random.randint(1100,size=10)
print(array)
mean=np.mean(array)
print(mean)
median=np.median(array)
print(median)
std=np.std(array)
print(std)

[ 607  579  388  982  873  703  488  270  497 1004]
639.1
593.0
235.8976261008152


In [10]:
#Create two random matrices A (3X2) and B (2X4). Compute their product using np.dot() and verify the shape of the result.
array1=np.random.randint(10,size=(3,2))
array2=np.random.randint(10,size=(2,4))
product=np.dot(array1,array2)
print(product)
print(product.shape)


[[34  7 43 34]
 [64 13 81 62]
 [51  9 65 34]]
(3, 4)


In [11]:
#Solve the following system using np.linalg.solve():2x + y = 5, x y = 1.
A=np.array([[2,1],[1,1]])
b=np.array([5,1])
x=np.linalg.solve(A,b)
print(x)


[ 4. -3.]


In [12]:
#Create a 6Ö 6 array with values from 1 to 36. Perform the following: Reshape into 6X6 matrix Extract the border elements into a separate array Set all border elements in the original matrix to 0 Print the nal modi ed matrix.
array=np.arange(1,37).reshape(6,6)
print(array)
border_elements=array[0,0],array[0,5],array[5,0],array[5,5]
print(border_elements)
array[0,:]=0
array[5,:]=0
array[:,0]=0
array[:,5]=0
print(array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
(np.int64(1), np.int64(6), np.int64(31), np.int64(36))
[[ 0  0  0  0  0  0]
 [ 0  8  9 10 11  0]
 [ 0 14 15 16 17  0]
 [ 0 20 21 22 23  0]
 [ 0 26 27 28 29  0]
 [ 0  0  0  0  0  0]]
